---
- hosts: localhost 
  become: yes
  tasks:
    - name: Install Packages 
      yum: 
        name: 
           - curl 
           - git
           - unzip
           - wget
           - bind-utils
           - yum-utils
           - lvm2
           - device-mapper-persistent-data
        state: present 

    - name: create Consul group
      group:
         name: consul 

    - name: create Consul user
      user:
         name: consul 
         group: consul 
         createhome: no

    - name: Unzip Vault Binary
      unarchive: 
        src: https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip dest=/etc/tempdownload
        dest: /usr/local/bin

    - name: Unzip Consul binary 
      unarchive: 
        src: https://releases.hashicorp.com/consul/1.8.0/consul_1.8.0_linux_amd64.zip
        dest: /usr/local/bin
        owner: root
        group: consul

    - name: Unzip Nomad binary
      unarchive:
        src: https://releases.hashicorp.com/nomad/0.12.8/nomad_0.12.8_linux_amd64.zip
        dest: /usr/local/bin

    - name: Unzip Terraform binary
      unarchive: 
        src: https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
        dest: /usr/local/bin

    - name: Unzip Packer binary  
      unarchive:
        src: https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
        dest: /usr/local/bin

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes