---
- hosts: localhost 
  become: yes 
  tasks: 

    - name: configure systemd
      copy: 
         src: /home/tharris/GCP-instance/files/consul.service
         dest: /etc/systemd/system 
      
    - name: create consul directory
      file:
         path: /etc/consul.d
         state: directory

    - name: add consul configuration (server)
      copy: 
         src: /home/tharris/GCP-instance/files/consul.hcl
         dest: /etc/consul.d

    - name: enable console service
      systemd:
        state: enabled
        name: consul

    - name: start consul systemd
      systemd:
         state: started
         name: consul 