---
- hosts: localhost 
  become: yes 
  tasks: 

    - name: configure systemd
      copy: 
         src: /home/tharris/GCE-instance/files/consul.service
         dest: /etc/systemd/system 
      
    - name: create consul directory
      file:
         path: /etc/consul.d
         state: directory

    - name: add consul configuration (server)
      copy: 
         src: /home/tharris/GCE-instance/files/consul.hcl
         dest: /etc/consul.d/
         owner: consul
         group: consul
         mode: '640' 

    - name: start consul systemd
      systemd:
         state: started
         name: consul 
         enabled: true 