---
- hosts: localhost 
  become: yes 
  tasks: 

    - name: configure systemd
      copy: 
         src: /home/tharris/GCE-instance/files/consul.service
         dest: /etc/systemd/system 
      
    - name: create consul directory
      file:
         path: /etc/consul.d
         state: directory

    - name: add consul configuration (server)
      copy: 
         src: /home/tharris/GCE-instance/files/server-config.json
         dest: /etc/consul.d

    - name: start consul systemd
      systemd:
         state: started
         name: consul 